name: CI

on:
  push:
    branches:
      - main

env:
  REGISTRY: "ghcr.io/goboden/lf-notifier"
  IMAGE_NAME: "bot"
  CONTAINER_NAME: "bot"
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build and push

        run: |
          tag="$(echo $GITHUB_SHA | head -c7)"
          echo TAG $tag
          docker build -t $REGISTRY/$IMAGE_NAME:${tag} .
          echo $GHCR_TOKEN | docker login ghcr.io -u goboden --password-stdin
          docker push $REGISTRY/$IMAGE_NAME:${tag}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
          script: |
            tag="$(echo $GITHUB_SHA | head -c7)"
            echo $GHCR_TOKEN | docker login ghcr.io -u goboden --password-stdin
            docker stop $CONTAINER_NAME
            docker rm $CONTAINER_NAME

            export TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            
            docker run -e TOKEN -d \
            --restart always \
            --name $CONTAINER_NAME \
            $REGISTRY/$IMAGE_NAME:${tag}